export const items1 = [
  {
    id: 1,
    image: "/Screenshot_1.png",
    link: "https://web-illa-cloud.netlify.app",
    description: "web-illa-cloud.netlify.app",
    title: "Web-illa-cloud",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 100,
  },
  {
    id: 2,
    image: "/Screenshot_2.png",
    link: "https://magedeveloper.netlify.app",
    description: "magedeveloper.netlify.app",
    title: "Magedeveloper",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 200,
  },
  {
    id: 3,
    image: "/Screenshot_3.png",
    link: "https://fastgendev.netlify.app",
    description: "fastgendev.netlify.app",
    title: "Fastgendev",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 300,
  },
  {
    id: 4,
    image: "/Screenshot_4.png",
    link: "https://vuesneakers747.netlify.app",
    description: "vuesneakers747.netlify.app",
    title: "VueSneakers",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 400,
  },
  {
    id: 5,
    image: "/Screenshot_5.png",
    link: "https://hyperwebdev.netlify.app",
    description: "hyperwebdev.netlify.app",
    title: "Hyperwebdev",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 500,
  },
  {
    id: 6,
    image: "/Screenshot_11.png",
    link: "https://webupstash.netlify.app/",
    description: "webupstash.netlify.app",
    title: "Upstash",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 550,
  },
  {
    id: 7,
    image: "/Screenshot_12.png",
    link: "https://freesets-api.netlify.app/",
    description: "freesets-api.netlify.app",
    title: "Freesets",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 600,
  },
  {
    id: 8,
    image: "/Screenshot_13.png",
    link: "https://mytestvue747.netlify.app/",
    description: "mytestvue747.netlify.app",
    title: "Mytestvue747",
    framework: "Vue.js",
    linkFramework: "https://vuejs.org/",
    imageFramework: "/vue.svg",
    library: "AOS",
    linkLibrary: "https://michalsnik.github.io/aos/",
    imageLibrary: "/AOS.svg",
    UIFrameworkT: "Tailwind CSS",
    linkUIFrameworkT: "https://tailwindcss.com/",
    imageUIFrameworkT: "/tailwindcss.svg",
    UIFrameworkP: "PrimeVue",
    linkUIFrameworkP: "https://primevue.org/",
    imageUIFrameworkP: "/PrimeVue.svg",
    Servis: "Netlify",
    linkServis: "https://www.netlify.com/",
    imageServis: "/netlify.svg",
    delay: 650,
  },
];
